### ISSUE TITLE
fetch 接口成功后能否返回一些文件信息

### ISSUE THREAD

**Issue by BiteBit** [qiniu/nodejs-sdk.v6#132]
你好。问题标题
比如文件的大小，文件的HASH，文件的mimetype等信息。
这样一方面可以减少用户再次通过文件名来get文件信息，给七牛带来服务器压力。
另一方便也给用户减少了开支。最主要的是用起来方便很多。

**Comment by longbai** [comment]
嗯，这个我们内部有在处理了

**Comment by BiteBit** [comment]
看到文档中fetch已经返回了hash,key
那么为什么不返回其他字段呢？
非常需要文件大小等字段啊！！！！

**Comment by longbai** [comment]
这个行为和上传接口是一致的

**Comment by longbai** [comment]
已经支持 fsize, mimetype 字段

**Comment by BiteBit** [comment]
终于支持了！
赞一个
