### ISSUE TITLE
fetcher 接口，超时后，下载未终止

### ISSUE THREAD

**Issue by BiteBit** [qiniu/nodejs-sdk.v6#135]
使用fetch接口下载，当超时发生时，fetch返回
```javascript
{
  code: -1,
  error: {
    [ConnectionTimeoutError: Request#1 timeout for 60000ms]
    name: 'ConnectionTimeoutError' 
  } 
}
```

但是，发现本次fetch并没有停止，并继续下载完文件。
而超时只是返回给我结果（无法该资源是由于太大，未下载完超时，还是确实无法下载），这样会导致该文件像丢如大海一样，再也找不到了。

能否加入一个超时停止下载的参数呢，而不是仅仅告诉我下载超时？

**Comment by longbai** [comment]
好的，我们明确下这个API 行为。

**Comment by simon-liubin** [comment]
这样的行为也算正常吧

**Comment by 963334657** [comment]
六年过去了，这个问题还是没有解决，就是用来坑钱的
