### ISSUE TITLE
出现异常时的返回结果为什么不是Error对象？

### ISSUE THREAD

**Issue by helloyou2012** [qiniu/nodejs-sdk.v6#149]
见代码：[https://github.com/qiniu/nodejs-sdk.v6/blob/master/qiniu/rpc.js#L55](https://github.com/qiniu/nodejs-sdk.v6/blob/master/qiniu/rpc.js#L55)，为什么改成了普通对象而不是直接将Error对象返回。code可以挂在Error对象上的呀。

**Comment by longbai** [comment]
多谢，这个我们后面会在新版本 sdk 作改进，
