### ISSUE TITLE
为什么要把qiniu.rs.PutPolicy改掉?

### ISSUE THREAD

**Issue by iyjian** [qiniu/nodejs-sdk.v6#151]
6.1.7中qiniu.rs.PutPolicy接收的是obj , 
function PutPolicy(putPolicyObj)
为什么到6.1.8中变成了
PutPolicy(scope, callbackUrl, callbackBody, returnUrl, returnBody,asyncOps, endUser, expires, persistentOps, persistentNotifyUrl)

**Comment by longbai** [comment]
不好意思，PutPolicy2 这个是 obj

**Comment by iyjian** [comment]
我知道啊,已经发现了,但是这样做不厚道哦,我们一升级就不行了,找了半天原因.

**Comment by longbai** [comment]
您说的是，这个是我的疏忽，后面会加强这方面的控制，抱歉给您添麻烦了。

**Comment by iyjian** [comment]
哈哈,太客气了
