### ISSUE TITLE
a spelling mistake found

### ISSUE THREAD

**Issue by douxing** [qiniu/nodejs-sdk.v6#177]
I believe there is a misspelling at [this line of the source file](https://github.com/qiniu/nodejs-sdk.v6/blob/master/qiniu/io.js#L22).

``` javascript
this.paras = params || {};
```
should be
``` javascript
this.params = params || {};
```

somebody please fix it if I am right.

**Comment by longbai** [comment]
多谢，我们改下

**Comment by longbai** [comment]
fixed in #178
