### ISSUE TITLE
刷新CDN缓存

### ISSUE THREAD

**Issue by bruceCzK** [qiniu/nodejs-sdk.v6#183]
有时候用第三方抓取的图片有问题，但是下载之后直接就进 CDN 了，需要刷新一下，请问是否有相关的接口可以调用？

**Comment by peaceful321** [comment]
有的，https://support.qiniu.com/hc/kb/article/134426
参考第三点；
建议有问题，可以直接提工单，找七牛的技术支持；谢谢

**Comment by bruceCzK** [comment]
恩。好的。
后来看了 qshell 的源码最后直接调用 HTTP API 了
POST http://fusion.qiniuapi.com/refresh {urls: Array}
