### ISSUE TITLE
可以移除掉 fileHandleForce 方法中的 console.log(body) 吗？

### ISSUE THREAD

**Issue by MopTym** [qiniu/nodejs-sdk.v6#195]
很多时候并不需要看到这些信息，当批处理数量较多时会被刷屏。

**Comment by MopTym** [comment]
https://github.com/qiniu/nodejs-sdk.v6/blob/master/qiniu/rs.js#L187

**Comment by peaceful321** [comment]
这个后续可以优化，
建议后面有问题，可以直接提交工单，联系技术支持，每天都有人回复的；

**Comment by MopTym** [comment]
好的谢谢
