### ISSUE TITLE
policy 未定义

### ISSUE THREAD

**Issue by abnerCrack** [qiniu/nodejs-sdk.v6#204]
把example里面 引用补全了把 。

**Comment by peaceful321** [comment]
你好，当前使用时候是有遇到什么问题么，可以通过提工单，七牛的技术支持，会第一时间进行回复的；

**Comment by Helloooooooooo** [comment]
/examples/upDemo.js这个文件的第九行。
var putPolicy = new qiniu.rs.PutPolicy2(new policy('bucket:key'));

policy是什么东西，并未定义。

这样的文档有点敷衍啊兄弟。
