### ISSUE TITLE
请不要使用sync-request

### ISSUE THREAD

**Issue by daozhihun** [qiniu/nodejs-sdk.v6#205]
我发现在上传的过程中，你们在zone.js是使用了sync-request。但是这样会导致服务器被阻塞掉，尤其是网络不好的时候。按照sync-request的官方文档：

You should not be using this in a production application. In a node.js application you will find that you are completely unable to scale your server. In a client application you will find that sync-request causes the app to hang/freeze. Synchronous web requests are the number one cause of browser crashes. For production apps, you should use then-request, which is exactly the same except that it is asynchronous.

因此麻烦你们不要同步处理网络请求，否则如果我们直接在服务端代码上传文件的话，并发度会显著下降。

**Comment by jingchen2222** [comment]
同意。另外，我在ATOM使用qiniu-uploader时候，使用sync-request会产生‘'unsafe-eval’ ’错误。这其实应该归因于ATOM自生的问题。但总归使用异步请求如urllib来替换sync-request，qiniu sdk的兼容性会更好些。

**Comment by peter4431** [comment]
刚刚因为 sync-request， 服务器阻塞了 2min， 官方不打算换只能自己手动改了。

**Comment by peter4431** [comment]
因为一个请求超时了，两分钟才报超时错误。

Error: connect ETIMEDOUT 115.231.182.36:80

**Comment by daozhihun** [comment]
过了这么长时间连个反应也没有，看来官方已经放弃治疗了。
犯了这么低级的错误，这么简单的fix都不愿意给，由此可见这个存储的质量。
奉劝大家不要为了省钱找这种野鸡公司的服务，肯定还有其他地方会被坑惨。

**Comment by ultrant** [comment]
在node.js上使用sync-request同步请求，绝对是一个脑残的决定，完全没有理解node.js开发的要领，一个node.js进程只有一个js主线程，hang住了就做不了其他事情了，所以网络操作都要做成异步的才行。

**Comment by GuGaobai1994** [comment]
https://github.com/qiniu/nodejs-sdk.v6/pull/237

**Comment by daozhihun** [comment]
居然还删评论，有问题说点坏话就不听了？
果断停止使用七牛。
