### ISSUE TITLE
fetch资源的时候域名是写死的，能不能改成可配置的啊？

### ISSUE THREAD

**Issue by benben1024** [qiniu/nodejs-sdk.v6#216]
Client.prototype.fetch = function(url, bucket, key, onret) {
  var bucketUri = getEncodedEntryUri(bucket, key);
  var fetchUrl = util.urlsafeBase64Encode(url);
  var uri = 'http://iovip-z1.qbox.me/fetch/' + fetchUrl + '/to/' + bucketUri;
  var digest = util.generateAccessToken(uri, null);
  rpc.postWithoutForm(uri, digest, onret);
}

uri是写死的、不同区域的根本用不了

**Comment by benben1024** [comment]
七牛真尼玛垃圾

**Comment by GuGaobai1994** [comment]
https://github.com/qiniu/nodejs-sdk.v6/pull/237
