### ISSUE TITLE
rs.Client.fetch  incorrect region

### ISSUE THREAD

**Issue by Bangood** [qiniu/nodejs-sdk.v6#233]
使用rs.Client.fetch转存第三方资源时，报incorrect region错误，我的存储空间为华南私有空间，需要在源码里将http://iovip.qbox.me改为http://iovip-z2.qbox.me才能解决，很不方便，能不能提供一个接口更改该host啊

**Comment by GuGaobai1994** [comment]
https://github.com/qiniu/nodejs-sdk.v6/pull/237
